api_login_check:
    path: /api/auth/login
    methods: ['POST']

api_register:
    path: /api/auth/register
    controller: App\Controller\AuthController::register
    methods: ['POST']

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
