version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
    depends_on:
      - database
      - mailer

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wplanner
    volumes:
      - mysql_data:/var/lib/mysql

  mailer:
    image: axllent/mailpit:latest
    ports:
      - "1026:1025"  # SMTP server
      - "8026:8025"  # Web interface

volumes:
  mysql_data: 