version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: production
      args:
        - NODE_ENV=production
    ports:
      - "8080:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - frontend_build:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - wplanner-network

  backend:
    build:
      context: ./backend
      args:
        - APP_ENV=prod
        - APP_DEBUG=0
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
      - APP_SECRET=${APP_SECRET}
      - APP_URL=${PROTOCOL}://${DOMAIN}
      - DATABASE_URL=${DATABASE_URL}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}
      - MAILER_DSN=${MAILER_DSN}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
    volumes:
      - backend_uploads:/var/www/html/public/uploads
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - wplanner-network

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    restart: unless-stopped
    networks:
      - wplanner-network

volumes:
  mysql_data:
    driver: local
  backend_uploads:
    driver: local
  frontend_build:
    driver: local

networks:
  wplanner-network:
    driver: bridge 