version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: ${NODE_ENV:-development}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=${API_URL:-http://localhost:80}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "${API_PORT:-80}:80"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    environment:
      - APP_ENV=${APP_ENV:-dev}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - DATABASE_URL=mysql://${DB_USER:-root}:${DB_PASSWORD:-root}@database:3306/${DB_NAME:-wplanner}
    depends_on:
      - database
      - mailer

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-wplanner}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - mysql_data:/var/lib/mysql

  mailer:
    image: axllent/mailpit:latest
    ports:
      - "1026:1025"  # SMTP server
      - "8026:8025"  # Web interface

volumes:
  mysql_data: 