services:
  # Backend API service
  - type: web
    name: wplanner-backend-app
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wplanner-db
          property: connectionString
      - key: APP_SECRET
        value: 2ca64f8d83b9e89f5f19d672841d6bb8
      - key: JWT_PASSPHRASE
        value: wedding2025

  # Frontend service
  - type: web
    name: wplanner-frontend-app
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://wplanner-backend-app.onrender.com

databases:
  - name: wplanner-db
    databaseName: wplanner
    plan: free
    ipAllowList: [] 