lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: wedding2025
    token_ttl: 604800 # 7 days
    user_id_claim: email
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        query_parameter:
            enabled: true
            name: token
    api_platform:
        check_path: /api/auth/login
        username_path: email
        password_path: password
    allow_no_expiration: false
    set_cookies: []
    remove_token_from_body_when_cookies_used: false 